version: '3'
services:
  api:
    command: run
    expose:
      - '4101'
    image: 'kelecorix/pollock:api'
    links:
      - 'db:dblink'
    external_links:
      - db_1
    ports:
      - '4101:4101'
    privileged: true
  db:
    environment:
      - POSTGRES_PASSWORD=pollock-starfish
      - POSTGRES_USER=pollock
    expose:
      - '5432'
    image: 'postgres:9.5'
    ports:
      - '35432:5432'
  frontend:
    command: run
    expose:
      - '4100'
    image: 'kelecorix/pollock:app'
    links:
      - 'db:dblink'
    external_links:
      - db_1
    ports:
      - '4100:4100'
    privileged: true
  nginx:
    command: run
    expose:
      - '80'
      - '443'
    image: 'kelecorix/pollock:nginx'
    links:
      - frontend
      - api
    external_links:
      - api_1
      - frontend_1
      - db_1
    ports:
      - '443:443'
      - '80:80'